---
- hosts: kubernetes
  user: root

  tasks:
  - name: deploy regapplication on kubernetes
    command: kubectl apply -f deployment.yml

  - name: deploy regapplication service in kubernetes
    command: kubectl apply -f service.yml

  - name: update deployment with new pods if image is updated in docker hub
    command: kubectl rollout restart deployment.apps/formfilling-regapp
