apiVersion: v1
kind: Service
metadata:
  name: formfilling-service

spec:
  selector:
    app: regapplication        # should match with selector of deployment manifest

  ports:
    - port: 80               # service port
      targetPort: 8080         # container port to access awebapplication  

  type: LoadBalancer

